title: BRF Utkiken
description: Hemsida för BRF Utkiken i Härnösand
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme 
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
